[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "libffi",
  "pkg-config",
  "blas",
  "lapack",
  "libcxx",
  "libxml2",
  "libxslt"
]

[variables]
PYTHON_VERSION = "3.11"


[start]
cmd = "gunicorn app:app --worker-class eventlet -w 1 -b 0.0.0.0:$PORT"